[pe_routers]
PE_1 ansible_host=192.168.93.146
PE_2 ansible_host=192.168.93.150

[p_routers]
P_1 ansible_host=192.168.93.149
P_2 ansible_host=192.168.93.147

[route_reflectors]
RR_1 ansible_host=192.168.93.148

[routers:children]
pe_routers
p_routers
route_reflectors

[routers:vars]
ansible_network_os=cisco.ios.ios
ansible_connection=network_cli
ansible_user=automatizacion
ansible_password=cisco123
# Forzar el motor Paramiko para mayor compatibilidad con IOL
ansible_network_cli_ssh_type=paramiko
# Inyectar los algoritmos antiguos
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o KexAlgorithms=+diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-rsa'
ansible_command_timeout=60
ansible_connect_timeout=60